### ISSUE TITLE
Interacting with the he-transformer

### ISSUE THREAD

**Issue by acoj1993** [pjattke/docker-he-transformer#1]
Hi,

thanks a lot for this repository, you have saved me a lot of time!

I have a question regarding the interaction with the he-transformer. Have you been using the docker image for your own tests? If yes, how exactly?
Have you also tried building the library directly on the Linux machine?

Thanks in advance.

**Comment by pjattke** [comment]
Hi @acoj1993, 
I'm glad that the files helped you! We had to invest a lot of time to make it work.

Yes, we have been using this Docker image for benchmarking he-transformer. The docker image includes the installation of the Python package (see [here](https://github.com/pjattke/docker-he-transformer/blob/33f685934580d8e29e1cf370aec1e96c6db2f29c/Dockerfile#L99)). Afterward you should be able to run `source external/venv-tf-py3/bin/activate` and within that environment there is the package installed. As an example, you can try running the [examples](https://github.com/IntelAI/he-transformer/tree/master/examples) from the he-transformer repository.

No, we have been using the Docker image from the beginning on. Are you facing any issues trying to install it locally?

**Comment by pjattke** [comment]
@acoj1993 As building the docker image took a very long time, you can also find a ready-to-go image at https://hub.docker.com/repository/docker/marblehe/base_ngraph-he.

**Comment by acoj1993** [comment]
Hey @pjattke.

Thank you! You have saved me some research time, again. I ran the examples successfully. Great!
Also thanks for the docker image, building the image is indeed a pain in the ass. I have had like 5 or 6 unsuccessful builds that failed after some 2 hours of building, I can only assume that you guys did as well.

Cheers :)
