### ISSUE TITLE
he-transformer with the GPU

### ISSUE THREAD

**Issue by acoj1993** [pjattke/docker-he-transformer#2]
Hi @pjattke,

Dd you maybe try running the library with the GPU? If yes, what changes did you have to make?

Cheers,
Aleksandar

**Comment by pjattke** [comment]
Hi @acoj1993 

Unfortunately, we did not try running it with the GPU as we were training very small models only. I would suggest opening a new ticket in the official [IntelAI/he-transformer](https://github.com/IntelAI/he-transformer/issues) repo by mentioning fboemer. He was super helpful in the issues we had and I'm sure he will help you figuring this out too.

Best regards,
Patrick

**Comment by acoj1993** [comment]
Aha, OK. Thanks for the suggestion, will do.

Cheers,
Aleksandar
